### ISSUE TITLE
Submitting a comment title longer than 50 char throws an error

### ISSUE THREAD

**Issue by fawcett** [gsiems/pTracker#2]
When you try to create a comment on an issue, if the title of the comment is longer than 50 characters, a database error is thrown.  

In my case, the offending title was auto-generated off of the issue title.

-------
runtime error

Warning caught during route execution: DBD::Pg::db do failed: ERROR:  value too long for type character varying(50) at /opt/ptrack/pTracker/lib/pTracker/DB.pm line 213.

/opt/ptrack/pTracker/lib/pTracker/DB.pm around line 213

210 
211     $self->log_query( $query, @ary );
212 
213     eval { $dbh->do( $query, undef, @ary ); };
214     if ($@) {
215         $rv{error}  = 'Failed to create record.';
216         $rv{errstr} = $dbh->errstr;

**Comment by gsiems** [comment]
1. Added code to limit the length of the default comment title to the length of the database column.  
 1. Increased the size of the database column.
 1. Verified that the maxlength of the web page form field was getting set.
